name: Build Cobalt APK (Optimal)
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Trống ổ cứng
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          
      - name: Clone Code
        uses: actions/checkout@v4

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Sync & Build
        env:
          SCCACHE_GHA_ENABLED: "true"
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$PATH:$PWD/depot_tools
          sed -i 's|src/.vpython3|.vpython3|g' DEPS || true
          
          gclient sync --no-history
          
          python3 cobalt/build/gn.py -p android-arm -c qa --use-sccache
          ninja -C out/android-arm_qa cobalt_apk

      - name: Trả file
        uses: actions/upload-artifact@v4
        with:
          name: cobalt-apk
          path: out/android-arm_qa/**/*.apk
